### PR TITLE
Added Ukrainian characters

### PR DESCRIPTION
**Pull request by YegorShtonda**
This chars are transliterated differently than in other Cyrillic languages

### CODE REVIEW

**Review by Trott — APPROVED** [review]
Looking at the table of romanization in https://en.wikipedia.org/wiki/Romanization_of_Ukrainian, this conforms with BGN/PCGN 1965, so at least there's an authoritative standard to refer to. Looks good to me.

**Comment by Trott** [comment]
@YegorShtonda Is it OK if I port these changes over to the `slug` module too for parity?

**Comment by simov** [comment]
Yep, looks good to me as well.

**Comment by YegorShtonda** [comment]
@Trott Yes of course

**Pull request merged**
