### PR TITLE
added swedish and norwegian special chars

### PR DESCRIPTION
**Pull request by T-Philipp**
@simov I've added some new chars for sv and nb.
Thank you for this great tool 😁👍

### CODE REVIEW

**Comment by T-Philipp** [comment]
Happy new years @Trott are you able to merge PR's? :)
We would really appreciate it

**Comment by simov** [comment]
@T-Philipp I think it might be helpful including a test for that locale where you demonstrate what this change solves. Also this have the added benefit of building the actual charmap inside the module.

**Comment by T-Philipp** [comment]
@simov 👍 sure, added the tests

**Comment by simov** [comment]
Published in v1.6.5

**Comment by T-Philipp** [comment]
@simov 
Thanks a lot 🙇‍♂️👍

**Pull request closed without merging**
