### PR TITLE
Added support for Serbian characters

### PR DESCRIPTION
**Pull request by slavkobabic**
Removed duplicate characters

Added Serbian Cyrillic characters.

Added Serbian latin characters.

Added tests for Serbian characters.

### CODE REVIEW

**Comment by dejangeci** [comment]
When will this be merged?

**Comment by simov** [comment]
Can we have only the Serbian characters added in this PR? 

I don't feel comfortable removing characters from other alphabets because quite frankly I don't know any of them. Javascript doesn't have a problem with duplicate keys. And it's not like thousands of duplicate keys, it's just a few.

At first it looked to me that some characters were removed from one alphabet in favor of another and I don't want to deal with that type of stuff. I'm not the original author of that peace of code either, so I'm not sure how these alphabets were added in the first place.

If anyone can add only the new alphabet I would gladly merge it :+1:

**Comment by slavkobabic** [comment]
No problem.

**Comment by simov** [comment]
Thank you! Published in v1.2.2

**Pull request merged**
