### PR TITLE
Feature: removing of leading/trailing separators

### PR DESCRIPTION
**Pull request by davedoesdev**
Also added a test which failed with previous code

### CODE REVIEW

**Comment by simov** [comment]
Hi, @davedoesdev, thanks for contributing. This, however, seems to be a breaking change. Also, should we remove leading/trailing separators? The previous issue https://github.com/simov/slugify/issues/37 was about the way we remove leading/trailing white space characters.

**Comment by davedoesdev** [comment]
The tests pass with the change.
The previous behaviour was to try to remove a single trailing separator but it wasn't working, so the the test I added failed.

**Comment by simov** [comment]
TBH I don't know what this syntax means:

```js
.replace('#{replacement}$', '')
```

I've never seen something like it and it doesn't seem to do anything (originally this code was written by someone else).

The code responsible for altering the separators is this:

```js
.replace(/[-\s]+/g, options.replacement || '-')
```

It searches for multiple space characters or multiple separator characters inside the string and replaces them with a single separator.

So in the case of `  foo bar baz  ` (with 2 blank leading/trailing spaces) because of the `.trim()` it will produce `foo-bar-baz`, but in the case of `--foo bar baz--` it will produce `-foo-bar-baz-`. 

There was no logic in this module to remove leading/trailing separators. If that was the initial intent then I can consider it a bug, but otherwise it might potentially be a breaking change for someone.

Let me know what do you think.

**Comment by davedoesdev** [comment]
```javascript
.replace('#{replacement}$', '')
```

looks like Ruby originally to me. It's not doing anything I agree.

I also agree this PR isn't necessary.

**Pull request closed without merging**
