### PR TITLE
Add German locale

### PR DESCRIPTION
**Pull request by schwigri**
In German, letters with an umlaut are transcribed without a diacritic and given an "e" when the diacritic cannot be used (e.g. in slugs). For example, see these pages (from both Germany and German-speaking Switzerland):

Page name | Slug
--- | ---
Staatsministerin für ... | [`staatsministerin-fuer`...](https://www.bundesregierung.de/breg-de/bundesregierung/staatsministerin-fuer-migration-fluechtlinge-und-integration)
Pass & Identitätskarte | [`pass-identitaetskarte`](https://www.zh.ch/de/mobilitaet/pass-identitaetskarte.html)
Zürich | [`www.zuerich.com`](https://www.zuerich.com/de)

### CODE REVIEW

**Comment by simov** [comment]
Thanks :+1:

**Comment by Soetens** [comment]
This does not seem to work for me, I see the correct conversions in an array but `ö` still returns as `o` and not `oe`. 
```
url = slugify(val, {
locale: locale,
lower : true
});
```

**Comment by schwigri** [comment]
@Soetens, please check your slugify version as well as the string passed to locale (it must only be `de`; for example, `de_CH` will not work).

You can see an example here: https://codesandbox.io/s/slugify-test-ppc27?file=/src/App.js

**Comment by Trott** [comment]
I wonder if ö being transliterated to oe ought to be the default. I would imagine German is the most frequent place to find ö. I'm not sure how it is typically transliterated when it appears in Swedish and other languages.

**Comment by schwigri** [comment]
Looking back, I also wonder if the capital variations should be converted to capital followed by lower case. For example, I think it would be better if `slugify("Örlikon", { locale: "de" }) === "Oerlikon"`, and then allow users to uppercase or lowercase themselves.

Of course, this means that when capital umlaut occurs in the middle of a word, it would have to be handled (e.g. `.toLocaleUpperCase()` if that's the intention). But, that allows the most flexibility as it is more difficult to convert the second capital to lowercase while keeping the first.

**Comment by schwigri** [comment]
> I wonder if ö being transliterated to oe ought to be the default (and so on for other letters containing umlauts). I would imagine German is the most frequent place to find ö. I'm not sure how it is typically transliterated when it appears in Swedish and other languages.

It appears that in Swedish and Hungarian, the umlaut characters are typically transcribed without adding an e.

| Page Name | Slug |
| --- | --- |
| Regeringsförklaringen |[.../regeringsforklaringen...](https://www.regeringen.se/tal/2020/09/regeringsforklaringen-den-8-september-2020/) |
| Rättsliga dokument | [.../rattsliga-dokument/](https://www.regeringen.se/rattsliga-dokument/) |
| Miniszterelnök | [.../miniszterelnok](https://kormany.hu/miniszterelnok) |

Because of that, as well as existing usage, I'd be against changing default behavior.

**Pull request merged**
