### PR TITLE
feat: add "trim" option

### PR DESCRIPTION
**Pull request by Trott**
Fixes: https://github.com/simov/slugify/issues/122

### CODE REVIEW

**Comment by Trott** [comment]
@davidlukerice

**Review by simov — APPROVED** [review]

**Comment by imjared** [comment]
Possible you could cut a new release with this change?

**Comment by Trott** [comment]
I think the hold-up was what to do about the Armenian support that was merged in. Ship it as-is? Remove it then ship? Or change it a bit and ship? I vote for ship as-is, but any of those are reasonable.

**Comment by simov** [comment]
I don't have a strong preference over the Armenian support either. Whatever approach we pick it will result in some characters not having the required quote.

**Comment by Trott** [comment]
> I don't have a strong opinion about the Armenian support either. Whatever approach we pick it will result in some characters not having the required quote.

OK, if you don't have a strong opinion, then let's ship it as it stands now and we can always revise it later. 

1.6.0 published.

**Pull request merged**
